### ISSUE TITLE
Reconsider the name ServiceResponseSchema.

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk-base-restclient#11]
Maybe `ServiceResponseMapper`, or else?

**Comment by muga** [comment]
Agree. I think that `ServiceResponseMapper` is better. Because the purpose is to create `SchemaWriter` (it seems that `SchemaWriter` is also not good so much but). But, I don't have other good candidates.

**Comment by dmikurube** [comment]
@muga Thanks. Pushed a fixing PR #30.

**Comment by dmikurube** [comment]
#30 is merged. Closing.
