### ISSUE TITLE
Handle type errors in (Jackson)ServiceValue and *ColumnWriters

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk-base-restclient#12]

**Comment by dmikurube** [comment]
@muga Some questions in the original util-web_api.

* [Boolean](https://github.com/muga/embulk-util-web_api/blob/25a123a10ea3bd5c9f5e32cd0d9743b8268a478d/src/main/java/org/embulk/util/web_api/writer/BooleanColumnWriter.java#L25)
* [Double](https://github.com/muga/embulk-util-web_api/blob/25a123a10ea3bd5c9f5e32cd0d9743b8268a478d/src/main/java/org/embulk/util/web_api/writer/DoubleColumnWriter.java#L23)
* [Json](https://github.com/muga/embulk-util-web_api/blob/25a123a10ea3bd5c9f5e32cd0d9743b8268a478d/src/main/java/org/embulk/util/web_api/writer/JsonColumnWriter.java#L27)
* [Long](https://github.com/muga/embulk-util-web_api/blob/25a123a10ea3bd5c9f5e32cd0d9743b8268a478d/src/main/java/org/embulk/util/web_api/writer/LongColumnWriter.java#L24)
* [String](https://github.com/muga/embulk-util-web_api/blob/25a123a10ea3bd5c9f5e32cd0d9743b8268a478d/src/main/java/org/embulk/util/web_api/writer/StringColumnWriter.java#L23)
* [Timestamp](https://github.com/muga/embulk-util-web_api/blob/25a123a10ea3bd5c9f5e32cd0d9743b8268a478d/src/main/java/org/embulk/util/web_api/writer/TimestampColumnWriter.java#L28)

1) Some technical reasons why `*value()` is used in Boolean, Double and Long / `asText()` is used for String and Timestamp / `toString()` is used for Json?
1-1) Broken down: `asText` v.s. `toString`, and how about unused `textValue`?
1-2) Broken down: how about `asBoolean`, `asDouble` and `asLong`?

2) In Json, special reasons to once convert into `String` and then parse that. Not to directly convert `JsonNode` to msgpack `Value`?

**Comment by muga** [comment]
```
Some technical reasons why *value() is used in Boolean, Double and Long / asText() is used for String and Timestamp / toString() is used for Json?
```
@dmikurube Good catch. It's just bad implementation in embulk-util-web_api. I didn't care of them. I don't check the source code of Jackson for now but, it sounds that the usage of asXXX methods is better than others?

```
In Json, special reasons to once convert into String and then parse that. Not to directly convert JsonNode to msgpack Value?
```
Do you have good idea to convert them directly? I didn't know about it at that time. We should take it if you have.

**Comment by dmikurube** [comment]
> @dmikurube Good catch. It's just bad implementation in embulk-util-web_api. I didn't care of them. I don't check the source code of Jackson for now but, it sounds that the usage of asXXX methods is better than others?

Not perfectly sure. In general, `as*` tries to convert the value in some way within Jackson. `*value` just returns its real representation. Then,
* If we want to take full control of type conversions by ourselves, we may want to use `*value` and implement conversions there.
* If we delegate conversions to Jackson, we'd just use `as*`.

To make it easy to track later problem investigation, it may be better to control type conversions by ourselves, but it's not a trivial decision.

> Do you have good idea to convert them directly? I didn't know about it at that time. We should take it if you have.

No special ideas at the moment. I wanted to confirm whether there ware some reasons or not. :)

**Comment by dmikurube** [comment]
@muga Seeing Jackson source code.

* JSON numeric ==> Java numeric: `as*` and `*value` are the same
* JSON numeric ==> Java text: `asText` formats numerics to texts. `textValue` returns `null`.
* JSON text ==> Java text: `as*` and `*value` are the same.
* JSON text ==> Java numeric: `as*` parses texts to numerics. `*Value` returns `0`.

The key points are numeric <=> text. If we'd like to control how numerics are formatted to texts, and how texts are parsed to numerics, we'd use `*Value` and handle conversions by ourselves by checking types beforehand.

**Comment by dmikurube** [comment]
`asBoolean` may be the most clear example.

If the library is requested to interpret a text in JSON as `boolean` in Java, Jackson's `asBoolean` recognizes only `"true"` and `"false"` -- no `TRUE`, `False`, or `0`.

It happens when the following JSON is responded:
```
{ "flag": "True" }
```
and the plugin is implemented:
```
        return SchemaWriterFactory.builder()
                .add("flag", Types.BOOLEAN)
```

**Comment by dmikurube** [comment]
One idea is just following Jackson's `as*` (meaning we assume only `"true"` and `"false"`) in the library of ours.

If developers need other kinds of `true`/`false`, it's somewhat possible to override by extending `ServiceValue` and `ServiceRecord` by themselves. I guess it is not a very popular case...

Since `as*` methods don't fail for typing reasons, error handling may not be needed.

**Comment by muga** [comment]
```
If developers need other kinds of true/false, it's somewhat possible to override by extending ServiceValue and ServiceRecord by themselves. I guess it is not a very popular case...

Since as* methods don't fail for typing reasons, error handling may not be needed.
```

Agree. Let's use `asXXX` methods in Jackson for now.

**Comment by muga** [comment]
>> Do you have good idea to convert them directly? I didn't know about it at that time. We should take it if you have.

> No special ideas at the moment. I wanted to confirm whether there ware some reasons or not. :)

Yea, we could extend msgpack-core or jackson-binding to do that. But now they don't provide it yet.

**Comment by dmikurube** [comment]
Got it. #31 is merged. Closing. Filed #32 just for the future.
