### ISSUE TITLE
Reconsider the name "*ColumnResposible"

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk-base-restclient#14]
The name `-Responsible` originally intended to represent "Do something on the column which this `*ColumnWriter` is responsible on".

For example, [`writeColumnResponsible`](https://github.com/dmikurube/embulk-base-restclient/blob/1732fa556b0fad9d2f46b7ee2dbce1f8cb21ccad/src/main/java/org/embulk/base/restclient/writer/ColumnWriter.java#L18) meant "write the column where this `ColumnWriter` is responsible on".

**Comment by dmikurube** [comment]
Another candidate: `InResponse` to represent the same? Found a (very long) example in Chromium:
* [`sanitizeValueInResponseToMinOrMaxAttributeChange`](https://chromium.googlesource.com/chromium/src.git/+/90aeec8f9af8ca08eab1baa40ee647b170b7d59b/third_party/WebKit/Source/core/html/forms/RangeInputType.cpp#276) looks representing "sanitize a value in which the `RangeInputType` instance is in response".
  * (`RangeInputType` represents `<input type="range" ...>`. This function (re-)sanitizes a value input from a user when `min` or `max` of `<input type="range" min="1" max="10">` is changed.)

**Comment by dmikurube** [comment]
@muga Similar with `Fragile`. Another naming discussion. What do you think?

**Comment by dmikurube** [comment]
Ah, that `InResponse` might mean "a reaction to min/max change"? Hmm,

**Comment by dmikurube** [comment]
The names are totally local in the library (`org.embulk.base.restclient.writer`), so this issue may not be much serious. Jfyi.

**Comment by muga** [comment]
Thank you for sharing your thoughts. 
```
originally intended to represent "Do something on the column which this ColumnWriter is responsible on".
```
I totally agree with you and your thoughts. Rather, that's natural I think. Almost objects (i.e. `ColumnWriter`) are responsible for the state changes on the fields (i.e. `Column`) that they have. If so, I think that we might be able to take short names in the almost cases as method names like `writeColumn` and `getColumn`. How about it?

**Comment by dmikurube** [comment]
@muga Agreed, and pushed a PR #29.

btw, calling them `writer` may be a bit confusing for a reason similar to our discussion on `write` and `PageLoadable` at #22. Will revisit that later.

**Comment by dmikurube** [comment]
#29 is merged. Closing.
