### ISSUE TITLE
Reconsider the name RestClientInputPlugin"Fragile"Base

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk-base-restclient#16]
The `-Fragile` originally meant a warning that unexpected failures may happen by using it casually: "Use the version without `Fragile` as far as possible."

**Comment by dmikurube** [comment]
One possible alternative may be `Unsafe`. From my knowledge in Chromium (C++) for example, they have many names like `-Unsafe` to represent not to use this casually:

* [`ReserveBytesUnsafe`](https://chromium.googlesource.com/chromium/src.git/+/90aeec8f9af8ca08eab1baa40ee647b170b7d59b/components/tracing/core/scattered_stream_writer.h#57)
* [`UnsafeResetForTesting`](https://chromium.googlesource.com/chromium/src.git/+/90aeec8f9af8ca08eab1baa40ee647b170b7d59b/base/synchronization/atomic_flag.cc#28): It also represents it's just for testing, not for use in the main code
* [`AsUTF8Unsafe`](https://chromium.googlesource.com/chromium/src.git/+/90aeec8f9af8ca08eab1baa40ee647b170b7d59b/base/files/file_path.cc#605)
* [`CallJavascriptFunctionUnsafe`](https://chromium.googlesource.com/chromium/src.git/+/90aeec8f9af8ca08eab1baa40ee647b170b7d59b/content/public/browser/web_ui.h#104)

**Comment by dmikurube** [comment]
@muga Let me share the discussion. What do you think about that "Fragile"? ;)

**Comment by muga** [comment]
Thank you for sharing your thoughts. I've sometimes seen `XXXUnsafe` and `UnsafeXXX` as Java classe names. It's good for me to use `Unsafe`:-) It seems that the word is commonly appended to the end of the class name. If that's true, how about `RestClientInputPluginBaseUnsafe`?

**Comment by dmikurube** [comment]
@muga Agreed. Pushed a PR #28 to rename with `Unsafe` with comments.

**Comment by dmikurube** [comment]
#28 is merged. Closing.
