### ISSUE TITLE
Reconsider the name "PageLoadable/loadPage".

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk-base-restclient#22]
> "load" might confuse users. How about "write"?

from https://github.com/dmikurube/embulk-base-restclient/pull/20#pullrequestreview-18715461

**Comment by dmikurube** [comment]
@muga It's true that it's **writing** to `PageBuilder`, but considering that the plugin is input, the method is described as 1) to read/fetch/get some data from a REST service, and 2) to store the data to `PageBuilder`. The "main purpose" would be rather getting data.

Agreed that **load** is confusing since load does not describe the direction very well...

What do you think calling this `acquire`, `obtain`, `scrape`, or `fetch` data?

**Comment by muga** [comment]
I think that your point is really good. The main purpose of this part is "get data from a REST service". We can take one of your candidates shown in the above your comment.

Or how about `ingest`? It seems that the meaning of `ingest` is both of "get" and "consume".

**Comment by dmikurube** [comment]
@muga `ingest` sounds nice to me! Let's go ahead with `ingest`. :)

**Comment by dmikurube** [comment]
@muga Pushed a PR for this: https://github.com/dmikurube/embulk-base-restclient/pull/27

**Comment by dmikurube** [comment]
#27 is merged. Closing.
