### ISSUE TITLE
Revisit how to call ValueLocator

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk-base-restclient#23]
https://github.com/dmikurube/embulk-base-restclient/blob/cb6eca71a2407fb2c4fe205d976633569476ddc0/src/main/java/org/embulk/base/restclient/record/JacksonServiceRecord.java#L16-L19

From https://github.com/dmikurube/embulk-base-restclient/pull/20#discussion_r98083859
> a. The cost of those dynamic type checks. I think that it's really small instead of json value parsing but.
> b. Would be much better if the type check is executed at compile-time or before Embulk transaction starts.

**Comment by dmikurube** [comment]
@muga Quick summary:

>a. The cost of those dynamic type checks. I think that it's really small instead of json value parsing but.

The cost of `instanceof` is really cheap in recent Java (6+), especially if it's `true`. Furthermore, **in case it's `true`**, just "casting and catching `ClassCastException`" is faster than "`instanceof` then casting". I'd at least change this to "just casting", and leave some comments.

> b. Would be much better if the type check is executed at compile-time or before Embulk transaction starts.

Exactly. I'd try, but finally it may not be a very big problem as [a] above.

**Comment by muga** [comment]
Thank you for filing and commenting. I agree 👍  I also will find good idea. Please keep opening.

**Comment by dmikurube** [comment]
@muga Thanks. I just filed two types of fixes for this issue: #26 and #25.

#26 is the fix with just casting mentioned above.

#25 is another fix by static type resolving with generics. One concern is that developers need to take a bit care of typing...

**Comment by dmikurube** [comment]
#25 is merged. Closing.
